version: '3.8'
services:
  app:
    build: .
    ports: ["5000:5000"]
    env_file: .env
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7
volumes:
  mongo-data:
